### ISSUE TITLE
Markup cannot be imported from Flask since Flask 3.0.0

### ISSUE THREAD

**Issue by fantomH** [callmehero/flask-mdeditor#4]
There is a problem with importing Markup from Flask 3.0.0, thus flask-mdeditor no longer works.

from __init__.py

```
from flask import current_app, Markup, request, Blueprint, url_for, render_template_string, render_template, request
```

Markup has been removed from Flask.

The workaround, for now seems to downgrade Flask to its 2.3.3 version.

**Comment by redredkrovy** [comment]
I noticed that too.  I was looking for a CKEditor alternative.

**Comment by redredkrovy** [comment]
Looking at the init file you just need to remove Markup from the flask import line, then "pip install MarkupSafe" in your virtual environment, and add "from markupsafe import Markup" to the init file.  Works fine after that.

**Comment by zhenyong97** [comment]
@redredkrovy, thank you for your interest! Currently, it seems that the package is not compatible with Flask 3.0. I greatly welcome you to submit a PR to implement this functionality. In the meantime, I will also try to work on implementing this feature in the coming days.
